id: 'key'
key: 'xxx'
server: 'towny' # Ten server tren MySQL
tile: 1 # KM 50% thi ti le la 1.5, KM 100% thi ti le la 2
mysql:
 enabled: true
 host: localhost
 port: 3306
 user: user
 password: pass
 database: minefs