# Liên hệ doicard.vn để lấy ID và KEY
# Nhớ bảo họ thêm IP số server của bạn vào tài khoản
id: 'key'
key: 'xxx'
server: 'towny' # Tên này sẽ được log trên MySQL để dễ dàng thống kê
tile: 1 # KM 50% thì tỉ lệ là 1.5, 100% thì tỉ lệ là 2, không KM thì là 1
mysql:
 enabled: true
 host: localhost
 port: 3306
 user: user
 password: pass
 database: minefs